-- MySQL Script generated by MySQL Workbench
-- Fri Apr 27 11:44:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pomusdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pomusdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pomusdb` DEFAULT CHARACTER SET utf8 ;
USE `pomusdb` ;

-- -----------------------------------------------------
-- Table `pomusdb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomusdb`.`User` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(100) NOT NULL,
  `Latitude` FLOAT NOT NULL,
  `Longitude` FLOAT NOT NULL,
  `Address` VARCHAR(500) NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pomusdb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomusdb`.`Student` (
  `UserId` INT NOT NULL,
  PRIMARY KEY (`UserId`),
  CONSTRAINT `FK_Student_User`
    FOREIGN KEY (`UserId`)
    REFERENCES `pomusdb`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pomusdb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomusdb`.`Professor` (
  `UserId` INT NOT NULL,
  `Rating` FLOAT NULL,
  PRIMARY KEY (`UserId`),
  CONSTRAINT `FK_Professor_User`
    FOREIGN KEY (`UserId`)
    REFERENCES `pomusdb`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pomusdb`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomusdb`.`Subject` (
  `SubjectId` INT NOT NULL,
  `Name` VARCHAR(100) NULL,
  `Description` VARCHAR(400) NULL,
  PRIMARY KEY (`SubjectId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pomusdb`.`Topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomusdb`.`Topic` (
  `TopicId` INT NOT NULL,
  `Name` VARCHAR(100) NULL,
  `Description` VARCHAR(400) NULL,
  `TopicFatherId` INT NULL,
  `SubjectId` INT NULL,
  PRIMARY KEY (`TopicId`),
  INDEX `FK_Topic_TopicParent_idx` (`TopicFatherId` ASC),
  INDEX `FK_Topic_Subject_idx` (`SubjectId` ASC),
  CONSTRAINT `FK_Topic_TopicParent`
    FOREIGN KEY (`TopicFatherId`)
    REFERENCES `pomusdb`.`Topic` (`TopicId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Topic_Subject`
    FOREIGN KEY (`SubjectId`)
    REFERENCES `pomusdb`.`Subject` (`SubjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pomusdb`.`TopicProfessor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomusdb`.`TopicProfessor` (
  `TopicProfessorId` INT NOT NULL,
  `TopicId` INT NOT NULL,
  `ProfessorId` INT NOT NULL,
  `Price` DOUBLE(5,2) NULL,
  PRIMARY KEY (`TopicProfessorId`),
  INDEX `FK_TopicProfessor_Professor_idx` (`ProfessorId` ASC),
  INDEX `FK_TopicProfessor_Topic_idx` (`TopicId` ASC),
  CONSTRAINT `FK_TopicProfessor_Professor`
    FOREIGN KEY (`ProfessorId`)
    REFERENCES `pomusdb`.`Professor` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TopicProfessor_Topic`
    FOREIGN KEY (`TopicId`)
    REFERENCES `pomusdb`.`Topic` (`TopicId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pomusdb`.`Match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomusdb`.`Match` (
  `MatchId` INT NOT NULL,
  `StudentAccepted` BINARY(1) NULL,
  `ProfessorAccepted` BINARY(1) NULL,
  `TopicProfessorId` INT NOT NULL,
  `StudentId` INT NOT NULL,
  PRIMARY KEY (`MatchId`),
  INDEX `FK_TopicProfessorId_idx` (`TopicProfessorId` ASC),
  INDEX `FK_Match_Student_idx` (`StudentId` ASC),
  CONSTRAINT `FK_Match_TopicProfessor`
    FOREIGN KEY (`TopicProfessorId`)
    REFERENCES `pomusdb`.`TopicProfessor` (`TopicProfessorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Match_Student`
    FOREIGN KEY (`StudentId`)
    REFERENCES `pomusdb`.`Student` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pomusdb`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomusdb`.`Event` (
  `EventId` INT NOT NULL,
  `Rating` FLOAT NULL,
  `Comment` VARCHAR(100) NULL,
  `Latitude` FLOAT NULL,
  `Longitude` FLOAT NULL,
  `StartTime` DATETIME NULL,
  `EndTime` DATETIME NULL,
  `MatchId` INT NULL,
  PRIMARY KEY (`EventId`),
  INDEX `FK_Event_Match_idx` (`MatchId` ASC),
  CONSTRAINT `FK_Event_Match`
    FOREIGN KEY (`MatchId`)
    REFERENCES `pomusdb`.`Match` (`MatchId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pomusdb`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `pomusdb`;
INSERT INTO `pomusdb`.`User` (`UserId`, `UserName`, `Latitude`, `Longitude`, `Address`) VALUES (DEFAULT, 'Gabro', -23.546085, -46.757631, 'Rua Ernesto Zuanella 234');
INSERT INTO `pomusdb`.`User` (`UserId`, `UserName`, `Latitude`, `Longitude`, `Address`) VALUES (DEFAULT, 'Diego', -23.557818, -46.732322, 'Poli Bienio');
INSERT INTO `pomusdb`.`User` (`UserId`, `UserName`, `Latitude`, `Longitude`, `Address`) VALUES (DEFAULT, 'Jow', -23.55103, -46.721633, 'Shopping VIlla Lobos');

COMMIT;

