-- MySQL Script generated by MySQL Workbench
-- Sat Jun  2 09:32:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pomus_local
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pomus_local
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pomus_local` DEFAULT CHARACTER SET utf8 ;
USE `pomus_local` ;

-- -----------------------------------------------------
-- Table `pomus_local`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomus_local`.`User` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(100) NOT NULL,
  `Latitude` FLOAT NOT NULL,
  `Longitude` FLOAT NOT NULL,
  `Address` VARCHAR(500) NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pomus_local`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomus_local`.`Student` (
  `UserId` INT NOT NULL,
  PRIMARY KEY (`UserId`),
  CONSTRAINT `FK_Student_User`
    FOREIGN KEY (`UserId`)
    REFERENCES `pomus_local`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pomus_local`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomus_local`.`Professor` (
  `UserId` INT NOT NULL,
  `Rating` FLOAT NULL,
  PRIMARY KEY (`UserId`),
  CONSTRAINT `FK_Professor_User`
    FOREIGN KEY (`UserId`)
    REFERENCES `pomus_local`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pomus_local`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomus_local`.`Subject` (
  `SubjectId` INT NOT NULL,
  `Name` VARCHAR(100) NULL,
  `Description` VARCHAR(400) NULL,
  PRIMARY KEY (`SubjectId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pomus_local`.`Topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomus_local`.`Topic` (
  `TopicId` INT NOT NULL,
  `Name` VARCHAR(100) NULL,
  `Description` VARCHAR(400) NULL,
  `TopicFatherId` INT NULL,
  `SubjectId` INT NULL,
  PRIMARY KEY (`TopicId`),
  INDEX `FK_Topic_TopicParent_idx` (`TopicFatherId` ASC),
  INDEX `FK_Topic_Subject_idx` (`SubjectId` ASC),
  CONSTRAINT `FK_Topic_TopicParent`
    FOREIGN KEY (`TopicFatherId`)
    REFERENCES `pomus_local`.`Topic` (`TopicId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Topic_Subject`
    FOREIGN KEY (`SubjectId`)
    REFERENCES `pomus_local`.`Subject` (`SubjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pomus_local`.`TopicProfessor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomus_local`.`TopicProfessor` (
  `TopicProfessorId` INT NOT NULL,
  `TopicId` INT NOT NULL,
  `ProfessorId` INT NOT NULL,
  `Price` DOUBLE(5,2) NULL,
  PRIMARY KEY (`TopicProfessorId`),
  INDEX `FK_TopicProfessor_Professor_idx` (`ProfessorId` ASC),
  INDEX `FK_TopicProfessor_Topic_idx` (`TopicId` ASC),
  CONSTRAINT `FK_TopicProfessor_Professor`
    FOREIGN KEY (`ProfessorId`)
    REFERENCES `pomus_local`.`Professor` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TopicProfessor_Topic`
    FOREIGN KEY (`TopicId`)
    REFERENCES `pomus_local`.`Topic` (`TopicId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pomus_local`.`Match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomus_local`.`Match` (
  `MatchId` INT NOT NULL,
  `StudentAccepted` BINARY(1) NULL,
  `ProfessorAccepted` BINARY(1) NULL,
  `TopicProfessorId` INT NOT NULL,
  `StudentId` INT NOT NULL,
  PRIMARY KEY (`MatchId`),
  INDEX `FK_TopicProfessorId_idx` (`TopicProfessorId` ASC),
  INDEX `FK_Match_Student_idx` (`StudentId` ASC),
  CONSTRAINT `FK_Match_TopicProfessor`
    FOREIGN KEY (`TopicProfessorId`)
    REFERENCES `pomus_local`.`TopicProfessor` (`TopicProfessorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Match_Student`
    FOREIGN KEY (`StudentId`)
    REFERENCES `pomus_local`.`Student` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pomus_local`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomus_local`.`Event` (
  `EventId` INT NOT NULL,
  `Rating` FLOAT NULL,
  `Comment` VARCHAR(100) NULL,
  `Latitude` FLOAT NULL,
  `Longitude` FLOAT NULL,
  `StartTime` DATETIME NULL,
  `EndTime` DATETIME NULL,
  `MatchId` INT NULL,
  PRIMARY KEY (`EventId`),
  INDEX `FK_Event_Match_idx` (`MatchId` ASC),
  CONSTRAINT `FK_Event_Match`
    FOREIGN KEY (`MatchId`)
    REFERENCES `pomus_local`.`Match` (`MatchId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pomus_local`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `pomus_local`;
INSERT INTO `pomus_local`.`User` (`UserId`, `UserName`, `Latitude`, `Longitude`, `Address`) VALUES (1, 'Gabro', -23.546085, -46.757631, 'Rua Ernesto Zuanella 234');
INSERT INTO `pomus_local`.`User` (`UserId`, `UserName`, `Latitude`, `Longitude`, `Address`) VALUES (2, 'Diego', -23.557818, -46.732322, 'Poli Bienio');
INSERT INTO `pomus_local`.`User` (`UserId`, `UserName`, `Latitude`, `Longitude`, `Address`) VALUES (3, 'Jow', -23.55103, -46.721633, 'Shopping VIlla Lobos');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pomus_local`.`Student`
-- -----------------------------------------------------
START TRANSACTION;
USE `pomus_local`;
INSERT INTO `pomus_local`.`Student` (`UserId`) VALUES (3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pomus_local`.`Professor`
-- -----------------------------------------------------
START TRANSACTION;
USE `pomus_local`;
INSERT INTO `pomus_local`.`Professor` (`UserId`, `Rating`) VALUES (1, 4.5);
INSERT INTO `pomus_local`.`Professor` (`UserId`, `Rating`) VALUES (2, 4.8);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pomus_local`.`Subject`
-- -----------------------------------------------------
START TRANSACTION;
USE `pomus_local`;
INSERT INTO `pomus_local`.`Subject` (`SubjectId`, `Name`, `Description`) VALUES (1, 'Cálculo', 'Cálculo - Ensino Superior');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pomus_local`.`Topic`
-- -----------------------------------------------------
START TRANSACTION;
USE `pomus_local`;
INSERT INTO `pomus_local`.`Topic` (`TopicId`, `Name`, `Description`, `TopicFatherId`, `SubjectId`) VALUES (1, 'Integral', 'Integrais Simples, Duplas e Triplas', NULL, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pomus_local`.`TopicProfessor`
-- -----------------------------------------------------
START TRANSACTION;
USE `pomus_local`;
INSERT INTO `pomus_local`.`TopicProfessor` (`TopicProfessorId`, `TopicId`, `ProfessorId`, `Price`) VALUES (1, 1, 1, 50);
INSERT INTO `pomus_local`.`TopicProfessor` (`TopicProfessorId`, `TopicId`, `ProfessorId`, `Price`) VALUES (2, 1, 2, 75);

COMMIT;

